json.extract! article,
              :id,
              :entry_id,
              :title,
              :author,
              :content,
              :date,
              :url,
              :image_url,
              :viewed,
              :saved,
              :feed_id
